---
options:
  merge-default-rules: false
  # formatter: stylish
  formatter: stylish
  # output-file: 'sass-lint.html'
rules:
  extends-before-declarations: 2
  extends-before-mixins: 2
  leading-zero: 2
  mixins-before-declarations: 2
  no-color-keywords: 2
  no-duplicate-properties: 2
  no-empty-rulesets: 2
  no-invalid-hex: 2
  no-mergeable-selectors: 2
  no-misspelled-properties:
    - 2
    -
      extra-properties:
        - font-smooth
  no-trailing-zero: 2
  # no-transition-all: 2
  one-declaration-per-line: 2
  property-sort-order: 2
  quotes: 2
  single-line-per-selector: 2
  space-after-colon: 2
  space-after-comma: 2
  space-before-brace: 2
  url-quotes: 2
  zero-unit: 2
